blob.server.port: 6124
taskmanager.memory.process.size: 1536m
metrics.reporter.prom.port: 9249
jobmanager.rpc.address: flink-jobmanager
metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
jobmanager.memory.process.size: 1024m
query.server.port: 6125
rest.port: 8081
execution.checkpointing.interval: 30s
s3.access-key: minioadmin
s3.connection.ssl.enabled: false
s3.secret-key: minioadmin
s3.endpoint: http://minio:9000
parallelism.default: 2
taskmanager.numberOfTaskSlots: 2
metrics.reporters: prom
state.backend.type: hashmap
state.checkpoints.dir: s3://checkpoints/flink
s3.path.style.access: true
